src/SFA.DAS.EAS.Web/ViewModels/InvitationViewModel.cs
using System;
using SFA.DAS.EAS.Domain.Models.AccountTeam;
using SFA.DAS.EAS.Domain.Models.UserProfile;

namespace SFA.DAS.EAS.Web.ViewModels
{
    public class InvitationViewModel
    {
        public bool IsUser { get; set; }
        public long Id { get; set; }
        public long AccountId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Role Role { get; set; }
        public InvitationStatus Status { get; set; }
        public DateTime ExpiryDate { get; set; }
    }
}

src/SFA.DAS.EAS.Web/Controllers/InvitationController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using SFA.DAS.EAS.Domain.Configuration;
using SFA.DAS.EAS.Domain.Interfaces;
using SFA.DAS.EAS.Web.Authentication;
using SFA.DAS.EAS.Web.Orchestrators;
using SFA.DAS.EAS.Web.ViewModels;
using SFA.DAS.EmployerUsers.WebClientComponents;

namespace SFA.DAS.EAS.Web.Controllers
{
    
    [RoutePrefix("invitations")]
    public class InvitationController : BaseController
    {
        private readonly InvitationOrchestrator _invitationOrchestrator;
        
        private readonly EmployerApprenticeshipsServiceConfiguration _configuration;

        public InvitationController(InvitationOrchestrator invitationOrchestrator, IOwinWrapper owinWrapper, 
            IFeatureToggle featureToggle, IMultiVariantTestingService multiVariantTestingService, EmployerApprenticeshipsServiceConfiguration configuration, ICookieStorageService<FlashMessageViewModel> flashMessage) 
            : base(owinWrapper, featureToggle,multiVariantTestingService, flashMessage)
        {
            if (invitationOrchestrator == null)
                throw new ArgumentNullException(nameof(invitationOrchestrator));
            _invitationOrchestrator = invitationOrchestrator;
            _configuration = configuration;
            
        }

        [Route("invite")]
        public ActionResult Invite()
        {
            if (string.IsNullOrEmpty(OwinWrapper.GetClaimValue("sub")))
            {
                return View();
            }

            return RedirectToAction("Index", "Home");
        }
        
        [HttpGet]
        [AuthoriseActiveUser]
        [Route]
        public async Task<ActionResult> All()
        {
            if (string.IsNullOrEmpty(OwinWrapper.GetClaimValue("sub")))
            {
                return RedirectToAction("Index", "Home");
            }

            var model = await _invitationOrchestrator.GetAllInvitationsForUser(OwinWrapper.GetClaimValue("sub"));

            return View(model);
        }

        [HttpGet]
        [Authorize]
        [Route("view")]
        public async Task<ActionResult> View(string invitationId)
        {
            if (string.IsNullOrEmpty(OwinWrapper.GetClaimValue("sub")))
            {
                return RedirectToAction("Index", "Home");
            }

            var invitation = await _invitationOrchestrator.GetInvitation(invitationId);

            return View(invitation);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        [Route("accept")]
        public async Task<ActionResult> Accept(long invitation, UserInvitationsViewModel model)
        {
            if (string.IsNullOrEmpty(OwinWrapper.GetClaimValue("sub")))
            {
                return RedirectToAction("Index", "Home");
            }

            var invitationItem = model.Invitations.SingleOrDefault(c => c.Id == invitation);

            if (invitationItem == null)
            {
                return RedirectToAction("Index", "Home");
            }

            await _invitationOrchestrator.AcceptInvitation(invitationItem.Id, OwinWrapper.GetClaimValue("sub"));
            
            var flashMessage = new FlashMessageViewModel
            {
                Headline = "Invitation accepted",
                Message = $"You can now access the {invitationItem.AccountName} account",
                Severity = FlashMessageSeverityLevel.Success
            };
            AddFlashMessageToCookie(flashMessage);


            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        [Route("create")]
        public async Task<ActionResult> Create(InviteTeamMemberViewModel model)
        {
            if (string.IsNullOrEmpty(OwinWrapper.GetClaimValue("sub")))
            {
                return RedirectToAction("Index", "Home");     
            }

            await _invitationOrchestrator.CreateInvitation(model, OwinWrapper.GetClaimValue("sub"));

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Route("register-and-accept")]
        public ActionResult AcceptInvitationNewUser()
        {
            var schema = System.Web.HttpContext.Current.Request.Url.Scheme;
            var authority = System.Web.HttpContext.Current.Request.Url.Authority;
            var c = new Constants(_configuration.Identity);
            return new RedirectResult($"{c.RegisterLink()}{schema}://{authority}/invitations");
        }


        [HttpGet]
        [Route("accept")]
        public ActionResult AcceptInvitationExistingUser()
        {
            return RedirectToAction("All");
        }


    }
}

src/SFA.DAS.EAS.Web/Views/Invitation/All.cshtml
@using SFA.DAS.EAS.Domain.Models.UserProfile
@model SFA.DAS.EAS.Web.OrchestratorResponse<SFA.DAS.EAS.Web.ViewModels.UserInvitationsViewModel>
@{
    ViewBag.Title = "Invitations";
    ViewBag.HideNav = "true";
}



<div class="grid-row">
    <div class="column-two-thirds">
        <h1 class="heading-xlarge">Invitations</h1>
        @if (Model.Data.Invitations.Count == 0)
        {
            <p>You have no invitations. Invitations expire after 7 days.</p>
            <p><a class="button" href="@Url.Action("Index","Home")">Return to your profile</a></p>
        }
        else
        {
            
            <form method="post" action="@Url.Action("Accept","Invitation")">
                @Html.AntiForgeryToken()
                <table>
                    <thead>
                        <tr>
                            <th scope="col">Account name</th>
                            <th scope="col">What you can do</th>
                            <th scope="col">Expires in</th>
                            <th scope="col"><span class="vh">Action</span></th>
                        </tr>
                    </thead>

                    <tbody>
                        @for (var index = 0; index < Model.Data.Invitations.Count; index++)
                        {
                            var invitation = Model.Data.Invitations[index];
                            <tr>
                                <td>
                                    <div>@invitation.AccountName</div>
                                    <input type="hidden" name="Invitations[@index].AccountName" value="@invitation.AccountName"/>
                               
                                </td>
                                <td>
                                
                                    <div>@RoleStrings.GetRoleDescription((Role)invitation.RoleId)</div>
                                </td>
                                <td>
                                 
                                    <div>@invitation.ExpiryDays()</div>
                                </td>
                                <td class="link-right">
                                    <div>
                                        <input type="hidden" name="Invitations[@index].Id" value="@invitation.Id" />
                                        <button type="submit" id="invitationId" value="@invitation.Id" name="invitation" class="link-button" title="Accept invite to @invitation.AccountName">Accept invite</button>
                                    </div>
                                 
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </form>
        }
    </div>
</div>

@if (Model.Data.ShowBreadCrumbs)
{
    @section breadcrumb {
        <div class="breadcrumbs">
            <ol role="navigation">
                <li><a href="/">Your accounts</a></li>
                <li>Invitations</li>
            </ol>
        </div>
    }
}

src/SFA.DAS.EAS.Web/Views/Invitation/Index.cshtml
@{ViewBag.Title = "Invitations pending"; }
<div class="grid-row">
    <div class="column-two-thirds">
        <h1 class="heading-xlarge">Invitations pending</h1>
        <p>You have one or more pending invitations to an employer account. Please follow the link below to sign in or register as a new user</p>
        <p><a class="button button-start" href="@Url.Action("All","Invitation")">Sign in or register</a></p>
    </div>
</div>

src/SFA.DAS.EAS.Web/Views/Invitation/Invite.cshtml
@{ViewBag.Title = "Invitations pending"; }
<div class="grid-row">
    <div class="column-two-thirds">
        <h1 class="heading-xlarge">Invitations pending</h1>
        <p>You have one or more pending invitations to an employer account. Please follow the link below to sign in or register as a new user</p>
        <p><a class="button button-start" href="@Url.Action("All","Invitation")">Sign in or register</a></p>
    </div>
</div>

src/SFA.DAS.EAS.Web/Views/Invitation/View.cshtml
@using SFA.DAS.EAS.Domain.Models.UserProfile
@model SFA.DAS.EAS.Web.OrchestratorResponse<SFA.DAS.EAS.Domain.Models.AccountTeam.InvitationView>
@{
    ViewBag.Title = "Accept invitation";
    ViewBag.HideNav = "true";
}

<div class="grid-row">
    <div class="column-two-thirds">
        <h1 class="heading-medium">Accept invitation</h1>
        <form method="POST" action="@Url.Action("Accept")">
            <table class="th-nopadding">
                <thead>
                    <tr>
                        <th scope="col" style="padding-top: 0"></th>
                        <th scope="col" class="" style="padding-top: 0"></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Account</td>
                        <td>@Model.Data.AccountName</td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td>@Model.Data.Email</td>
                    </tr>
                    <tr>
                        <td>What you can do</td>
                        <td>@RoleStrings.GetRoleDescription((Role)Model.Data.RoleId)</td>
                    </tr>
                    <tr>
                        <td>Status</td>
                        <td>@Model.Status.ToString()</td>
                    </tr>
                </tbody>
            </table>
            <p></p>
            <input type="hidden" id="invitationId" name="invitationId" value="@Model.Data.Id" />
            <button type="submit" class="button" id="accept">Accept</button>
        </form>
    </div>
</div>