src/SFA.DAS.EAS.Web/Controllers/EmployerAccountOrganisationController.cs
using System;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using SFA.DAS.EAS.Domain.Interfaces;
using SFA.DAS.EAS.Domain.Models.Account;
using SFA.DAS.EAS.Domain.Models.Organisation;
using SFA.DAS.EAS.Web.Authentication;
using SFA.DAS.EAS.Web.Orchestrators;
using SFA.DAS.EAS.Web.ViewModels;
using SFA.DAS.EAS.Web.ViewModels.Organisation;
using SFA.DAS.NLog.Logger;

namespace SFA.DAS.EAS.Web.Controllers
{
    [Authorize]
    [RoutePrefix("accounts/organisations")]
    public class EmployerAccountOrganisationController : BaseController
    {
        private readonly OrganisationOrchestrator _orchestrator;
        private readonly IMapper _mapper;
        private readonly ILog _logger;

        public EmployerAccountOrganisationController(
            IOwinWrapper owinWrapper,
            OrganisationOrchestrator orchestrator,
            IFeatureToggle featureToggle,
            IMultiVariantTestingService multiVariantTestingService,
            IMapper mapper,
            ILog logger,
            ICookieStorageService<FlashMessageViewModel> flashMessage) 
            :base(owinWrapper, featureToggle,multiVariantTestingService, flashMessage)
        {
            _orchestrator = orchestrator;
            _mapper = mapper;
            _logger = logger;
        }

        [HttpGet]
        [Route("add")]
        public ActionResult AddOrganisation()
        {
            return View("AddOrganisation",
                new OrchestratorResponse<AddLegalEntityViewModel> {Data = new AddLegalEntityViewModel()});
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("add")]
        public async Task<ActionResult> AddOrganisation(AddLegalEntityViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var orgTypeErrorResponse = new OrchestratorResponse<AddLegalEntityViewModel>
                {
                    Data = model
                };

                orgTypeErrorResponse.Data.AddErrorsFromModelState(ModelState);

                orgTypeErrorResponse.Status = HttpStatusCode.BadRequest;
                orgTypeErrorResponse.FlashMessage = new FlashMessageViewModel
                {
                    Severity = FlashMessageSeverityLevel.Error,
                    ErrorMessages = orgTypeErrorResponse.Data.ErrorDictionary,
                    Headline = "Errors to fix",
                    Message = "Check the following details:"
                };
                return View(orgTypeErrorResponse);
            }

            OrchestratorResponse<OrganisationDetailsViewModel> response;

            //TODO this can be removed once we determine which is slow in prod
            var stopwatch = new System.Diagnostics.Stopwatch();
            try
            {
                
                stopwatch.Start();
                switch (model.OrganisationType)
                {
                    case OrganisationType.Charities:
                        response = await FindCharity(model.CharityRegistrationNumber, model.HashedAccountId, OwinWrapper.GetClaimValue(@"sub"));
                        break;
                    case OrganisationType.CompaniesHouse:
                        response = await FindCompany(model.CompaniesHouseNumber, model.HashedAccountId, OwinWrapper.GetClaimValue(@"sub"));

                        break;
                    case OrganisationType.PublicBodies:
                        var searchResponse = await FindPublicSectorOrganisation(model.PublicBodyName, model.HashedAccountId, OwinWrapper.GetClaimValue(@"sub"));

                        if (searchResponse.Status == HttpStatusCode.OK)
                        {
                            if (searchResponse.Data.Results.Data.Count != 1 ||
                                searchResponse.Data.Results.Data.All(x => x.AddedToAccount))
                            {
                                return View("ViewPublicSectorOrganisationSearchResults", searchResponse);
                            }

                            response = new OrchestratorResponse<OrganisationDetailsViewModel>
                            {
                                Data = searchResponse.Data.Results.Data.FirstOrDefault(),
                                Status = searchResponse.Status
                            };
                        }
                        else
                        {
                            response = new OrchestratorResponse<OrganisationDetailsViewModel>
                            {
                                Data = new OrganisationDetailsViewModel(),
                                Status = searchResponse.Status
                            };
                            response.Data.ErrorDictionary = searchResponse.Data.ErrorDictionary;
                        }

                        break;

                    case OrganisationType.Other:

                        response = new OrchestratorResponse<OrganisationDetailsViewModel>
                        {
                            Data = new OrganisationDetailsViewModel()
                        };

                        return View("AddOtherOrganisationDetails", response);

                    default:
                        throw new NotImplementedException("Org Type Not Implemented");
                }
            }
            finally
            {
                stopwatch.Stop();

                _logger.Info($"Company Search for {model.OrganisationType} took {stopwatch.ElapsedMilliseconds /1000d}s");
            }

            

            if (response.Status == HttpStatusCode.OK)
            {
                //Removes empty address entries (i.e. ' , , ')
                var address = (response.Data?.Address ?? string.Empty).Replace(",", string.Empty);

                if (string.IsNullOrWhiteSpace(address))
                {
                    var addressViewModel = _mapper.Map<FindOrganisationAddressViewModel>(response.Data);

                    var addressResponse = new OrchestratorResponse<FindOrganisationAddressViewModel>
                    {
                        Data = addressViewModel
                    };

                    return View("FindAddress", addressResponse);
                }

                CreateOrganisationCookieData(response);

                return RedirectToAction("GatewayInform", "EmployerAccount", response.Data);
            }

            var errorResponse = new OrchestratorResponse<AddLegalEntityViewModel>
            {
                Data = model,
                Status = HttpStatusCode.OK
            };
            errorResponse.Data.ErrorDictionary = response.Data.ErrorDictionary;

            errorResponse.FlashMessage = new FlashMessageViewModel
            {
                Severity = FlashMessageSeverityLevel.Error,
                ErrorMessages = errorResponse.Data.ErrorDictionary,
                Headline = "Errors to fix",
                Message = "Check the following details:"
            };

            return View("AddOrganisation", errorResponse);
        }

        [HttpGet]
        [Route("custom/add")]
        public ActionResult AddCustomOrganisationDetails()
        {
            var response = new OrchestratorResponse<OrganisationDetailsViewModel>
            {
                Data = new OrganisationDetailsViewModel()
            };

            return View("AddOtherOrganisationDetails", response);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("custom/add")]
        public async Task<ActionResult> AddOtherOrganisationDetails(OrganisationDetailsViewModel model)
        {
            var response = await _orchestrator.ValidateLegalEntityName(model);

            if (response.Status == HttpStatusCode.BadRequest)
            {
                return View("AddOtherOrganisationDetails", response);
            }

            model.Type = OrganisationType.Other;

            var addressModel = new OrchestratorResponse<FindOrganisationAddressViewModel>
            {
                Data = _mapper.Map<FindOrganisationAddressViewModel>(response.Data)
            };

            return View("FindAddress", addressModel);
            
        }

        [HttpPost]
        [Route("address/find")]
        public ActionResult FindAddress(FindOrganisationAddressViewModel request)
        {
            var response = new OrchestratorResponse<FindOrganisationAddressViewModel>
            {
                Data = request,
                Status = HttpStatusCode.OK
            };

            if (!string.IsNullOrEmpty(request.OrganisationAddress))
            {
                var organisationDetailsViewModel = _orchestrator.StartConfirmOrganisationDetails(request);
                
                CreateOrganisationCookieData(organisationDetailsViewModel);

                return RedirectToAction("GatewayInform", "EmployerAccount");
            }

            return View(response);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("address/select")]
        public async Task<ActionResult> SelectAddress(FindOrganisationAddressViewModel request)
        {
            var response = await _orchestrator.GetAddressesFromPostcode(request);

            if (response?.Data?.Addresses != null && response.Data.Addresses.Count == 1)
            {
                var viewModel = _mapper.Map<AddOrganisationAddressViewModel>(request);

                viewModel.Address = response.Data.Addresses.Single();

                var addressResponse = new OrchestratorResponse<AddOrganisationAddressViewModel>
                {
                    Data = viewModel,
                    Status = HttpStatusCode.OK
                };

                return View("AddOrganisationAddress", addressResponse);
            }

            return View(response);
        }
        
        [HttpGet]
        [Route("address/update")]

src/SFA.DAS.EAS.Web/Views/EmployerAccountOrganisation/AddOrganisationAddress.cshtml
@model SFA.DAS.EAS.Web.OrchestratorResponse<SFA.DAS.EAS.Web.ViewModels.Organisation.AddOrganisationAddressViewModel>
@{ViewBag.PageID = "page-extra-add-organisation-address"; }
@{
    ViewBag.Title = "Add Organisation Address";
    ViewBag.Section = "organisations";
    ViewBag.HideNav = "true";
}
<div class="grid-row">
    <div class="column-two-thirds">
        <h1 class="heading-xlarge">
            Enter your organisation's address
        </h1>
        <p class="lede">Use your organisation's main address, such as your head office.</p>
        <form action="@Url.Action("UpdateOrganisationAddress")" method="POST" novalidate>
            @Html.AntiForgeryToken()
            <div class="form-group @(!string.IsNullOrEmpty(Model.Data.Address.AddressFirstLineError) ? "error" : "")">
                <label for="AddressFirstLine">
                    <span class="form-label-bold">House number or name, building or street</span>
                    @if (!string.IsNullOrEmpty(Model.Data.Address.AddressFirstLineError))
                    {
                        <span class="error-message" id="error-message-address">@Model.Data.Address.AddressFirstLineError</span>
                    }
                </label>
                <input type="text" id="AddressFirstLine" name="Address.addressFirstLine" value="@Model.Data.Address.AddressFirstLine" class="form-control" required="required" aria-required="true"
                       @(!string.IsNullOrEmpty(Model.Data.Address.AddressFirstLineError) ? "aria-invalid=true aria-describedby=error-message-address" : "" ) />
            </div>
            <div class="form-group">
                <label for="AddressSecondLine">
                    <span class="form-label-bold">Address line 2 (optional)</span>
                </label>
                <input type="text" id="AddressSecondLine" name="Address.addressSecondLine" value="@Model.Data.Address.AddressSecondLine" class="form-control" />
            </div>
            <div class="form-group  @(!string.IsNullOrEmpty(Model.Data.Address.TownOrCityError) ? "error" : "")">
                <label for="TownOrCity">
                    <span class="form-label-bold">Town or city</span>
                    @if (!string.IsNullOrEmpty(Model.Data.Address.TownOrCityError))
                    {
                        <span class="error-message" id="error-message-town">@Model.Data.Address.TownOrCityError</span>
                    }
                </label>
                <input type="text" id="TownOrCity" name="Address.townOrCity" value="@Model.Data.Address.TownOrCity" class="form-control" required="required" aria-required="true"
                       @(!string.IsNullOrEmpty(Model.Data.Address.TownOrCityError) ? "aria-invalid=true aria-describedby=error-message-town" : "" ) />
            </div>
            <div class="form-group">
                <label for="County">
                    <span class="form-label-bold">County (optional)</span>
                </label>
                <input type="text" id="County" name="Address.county" value="@Model.Data.Address.County" class="form-control" />
            </div>
            <div class="form-group  @(!string.IsNullOrEmpty(Model.Data.Address.PostcodeError) ? "error" : "")">
                <label for="Postcode">
                    <span class="form-label-bold">Postcode</span>
                    @if (!string.IsNullOrEmpty(Model.Data.Address.PostcodeError))
                    {
                        <span class="error-message" id="error-message-postcode">@Model.Data.Address.PostcodeError</span>
                    }
                </label>
                <input type="text" id="Postcode" name="Address.postcode" value="@Model.Data.Address.Postcode" class="form-control" required="required" aria-required="true"
                       @(!string.IsNullOrEmpty(Model.Data.Address.PostcodeError) ? "aria-invalid=true aria-describedby=error-message-postcode" : "" ) />
            </div>
            <input type="hidden" id="organisationName" name="organisationName" value="@Model.Data.OrganisationName" />
            <input type="hidden" id="OrganisationReferenceNumber" name="OrganisationReferenceNumber" value="@Model.Data.OrganisationReferenceNumber" />
            <input type="hidden" id="OrganisationDateOfInception" name="OrganisationDateOfInception" value="@Model.Data.OrganisationDateOfInception" />
            <input type="hidden" id="OrganisationType" name="OrganisationType" value="@Model.Data.OrganisationType"/>
            <input type="hidden" id="PublicSectorDataSource" name="PublicSectorDataSource" value="@Model.Data.PublicSectorDataSource" />
            <input type="hidden" id="Sector" name="Sector" value="@Model.Data.Sector" />
            <input class="button" type="submit" value="Continue" />
        </form>
    </div>
</div>
@section breadcrumb {
    <div class="breadcrumbs">
        <ol role="navigation">
            <li><a href="@Url.Action("AddOrganisation", "EmployerAccountOrganisation")" class="back-link">Back</a></li>
        </ol>
    </div>
}

src/SFA.DAS.EAS.Web/Views/EmployerAccountOrganisation/AddOtherOrganisationDetails.cshtml
@model SFA.DAS.EAS.Web.OrchestratorResponse<SFA.DAS.EAS.Web.ViewModels.Organisation.OrganisationDetailsViewModel>
@{ViewBag.PageID = "enter-organisation-type"; }
@{
    ViewBag.Title = "Enter your organisation name";
    ViewBag.Section = "organisations";
    ViewBag.HideNav = "true";
}

<div class="grid-row">
    <div class="column-two-thirds">
        <h1 class="heading-xlarge">
            Enter your organisation name
        </h1>
        <form action="@Url.Action("AddOtherOrganisationDetails")" method="post">
            @Html.AntiForgeryToken()

            <div class="form-group @(!string.IsNullOrEmpty(Model.Data.NameError) ? "error" : "")">
                <label id="NewName-label" for="Name" class="form-label-bold">
                    <span class="form-label-bold">Name</span>
                    @if (!string.IsNullOrEmpty(Model.Data.NameError))
                    {
                        <span class="error-message" id="error-message-newname">@Model.Data.NameError</span>
                    }
                </label>
                @Html.TextBoxFor(
                    m => m.Data.Name,
                    new
                    {
                        Id = "Name",
                        Name = "Name",
                        @class = "form-control organisationName",
                        MaxLength = 100,
                        aria_required = "true",
                        aria_describedby = !string.IsNullOrEmpty(Model.Data.NameError) ? "error-message-newname" : ""
                    })
            </div>
            <div class="form-group">
                <button type="submit" class="button" id="accept">Continue</button>
                <a class="button-link" href="@Url.Action("Index", "Home")">Cancel</a>
            </div>
        </form>
    </div>
</div>
@section breadcrumb {
    <div class="breadcrumbs">
        <ol role="navigation">
            <li><a href="@Url.Action("AddOrganisation", "EmployerAccountOrganisation")" class="back-link">Back</a></li>
        </ol>
    </div>
}

src/SFA.DAS.EAS.Web/Views/EmployerAccountOrganisation/ConfirmOrganisationDetails.cshtml
@*@using SFA.DAS.EAS.Domain
@model SFA.DAS.EAS.Web.OrchestratorResponse<SFA.DAS.EAS.Web.Models.OrganisationDetailsViewModel>
@{ViewBag.PageID = "page-extra-confirm-organisation"; }
@{
    ViewBag.Title = "Confirm details";
    ViewBag.Section = "organisations";
    ViewBag.HideNav = "true";
}
<div class="grid-row">
    <div class="column-two-thirds">
        <h1 class="heading-xlarge">
            Confirm details
        </h1>

        <table>
            <tr>
                <th role="row">Organisation name</th>
                <td class="responsive-td">@Model.Data.Name</td>
            </tr>

            @if (Model.Data.Type != OrganisationType.PublicBodies && Model.Data.Type != OrganisationType.Other)
            {
                <tr>
                    <th role="row">Organisation number</th>
                    <td class="responsive-td">@Model.Data.ReferenceNumber</td>
                </tr>
            }
            <tr>
                <th role="row">Address</th>
                <td class="responsive-td">@Model.Data.Address</td>
            </tr>
        </table>

        <form action="@Url.Action("Confirm")" method="POST">
            @Html.AntiForgeryToken()
            <input type="hidden" id="legalEntityName" name="name" value="@Model.Data.Name" />
            <input type="hidden" id="legalEntityCode" name="code" value="@Model.Data.ReferenceNumber" />
            <input type="hidden" id="legalEntityAddress" name="address" value="@Model.Data.Address" />
            <input type="hidden" id="legalEntityIncorporationDate" name="incorporated" value="@Model.Data.DateOfInception"/>
            <input type="hidden" id="organisationType" name="organisationType" value="@Model.Data.Type" />
            <input type="hidden" id="userAuthorised" name="userIsAuthorisedToSign" value="true" />
            <input type="hidden" id="submit" name="submit" value="Sign"/>

            <p class="heading-medium">Is this correct?</p>

            <span>
                <input class="button" type="submit" value="Yes, continue" />
                <a class="button button-link" href="@Url.Action("AddOrganisation", new {AccountId = @Model.Data.HashedId})">No, search again</a>
            </span>
        </form>
        
    </div>
</div>
@section breadcrumb {
<div class="breadcrumbs">
    <ol role="navigation">
        <li><a href="@Url.Action("AddOrganisation", "EmployerAccountOrganisation")" class="back-link">Back</a></li>
    </ol>
</div>
}*@

src/SFA.DAS.EAS.Web/Views/EmployerAccountOrganisation/SearchForOrganisation.cshtml
@using SFA.DAS.EAS.Domain
@using SFA.DAS.EAS.Domain.Models.Organisation

@{ 
    ViewBag.PageID = "search-for-organisation";
    ViewBag.Title = "Search for your organisation";
    ViewBag.HideNav = "true";
}

<div class="grid-row">
    <div class="column-two-thirds">
        <h1 class="heading-xlarge">@ViewBag.Title</h1>
        <form>
            <div class="form-group">
                <label for="organisation-name">
                    <span class="form-label-bold">Enter name</span>
                </label>
                <input type="text" id="organisation-name" name="" value="" class="form-control" />
            </div>
            <input class="button" type="submit" value="Search" />
        </form>
    </div>
</div>

@section breadcrumb {
    <div class="breadcrumbs">
        <a href="@Url.Action("Index", "Home")" class="link-back">Back</a>
    </div>
}

src/SFA.DAS.EAS.Web/Views/EmployerAccountOrganisation/SelectAddress.cshtml
@model SFA.DAS.EAS.Web.OrchestratorResponse<SFA.DAS.EAS.Web.ViewModels.Organisation.SelectOrganisationAddressViewModel>
@{
    ViewBag.Title = "Select address";
    ViewBag.PageID = "select-organisation-address";
    ViewBag.HideNav = "true";
    var noAddressesFound = string.Empty;
}
<div class="grid-row">
    <div class="column-two-thirds">
        <h1 class="heading-xlarge">Find organisation address</h1>

        @if (Model.Status == HttpStatusCode.OK)
        {

            if (Model?.Data?.Addresses == null || !Model.Data.Addresses.Any())
            {

                noAddressesFound = $"No address found for the postcode {Model.Data.Postcode}";

            }
            else
            {
                <h2 class="heading-medium">Select your address:</h2>
                <ol class="search-results">
                    @foreach (var address in Model.Data.Addresses)
                    {
                        var url = Url.Action("UpdateOrganisationAddress", "EmployerAccountOrganisation", new
                        {
                            Model.Data.OrganisationName,
                            Model.Data.OrganisationReferenceNumber,
                            Model.Data.OrganisationType,
                            Model.Data.PublicSectorDataSource,
                            Model.Data.OrganisationStatus,
                            Model.Data.Sector,
                            Model.Data.OrganisationDateOfInception
                        });

                        url += $"&Address.{nameof(address.AddressFirstLine)}={address.AddressFirstLine}";
                        url += $"&Address.{nameof(address.AddressSecondLine)}={address.AddressSecondLine}";
                        url += $"&Address.{nameof(address.TownOrCity)}={address.TownOrCity}";
                        url += $"&Address.{nameof(address.County)}={address.County}";
                        url += $"&Address.{nameof(address.Postcode)}={address.Postcode}";

                        <li>
                            <a href="@url">
                                @address.ToString()
                            </a>
                        </li>
                    }
                </ol>
                <hr />
                <h2 class="heading-medium">Search again</h2>
            }
        }


        <form action="@Url.Action("SelectAddress")" method="POST" novalidate>
            @Html.AntiForgeryToken()
            <div class="form-group  @((!string.IsNullOrEmpty(Model.Data.PostcodeError) || !string.IsNullOrEmpty(noAddressesFound)) ? "error" : "")">
                <label for="Postcode">
                    <span class="form-label-bold">Enter postcode</span>
                    @if (!string.IsNullOrEmpty(Model.Data.PostcodeError) || !string.IsNullOrEmpty(noAddressesFound))
                    {
                        <span class="error-message" id="error-message-postcode">@Model.Data.PostcodeError @noAddressesFound</span>
                    }
                </label>

                <span>
                    <input type="text" id="Postcode" name="postcode" value="@Model.Data.Postcode" class="form-control" required="required" aria-required="true"
                           @((!string.IsNullOrEmpty(Model.Data.PostcodeError) || !string.IsNullOrEmpty(noAddressesFound)) ? "aria-invalid=true aria-describedby=error-message-postcode" : "" ) />
                    
                    
                </span>
            </div>
            <input type="hidden" id="organisationName" name="organisationName" value="@Model.Data.OrganisationName" />
            <input type="hidden" id="OrganisationReferenceNumber" name="OrganisationReferenceNumber" value="@Model.Data.OrganisationReferenceNumber" />
            <input type="hidden" id="OrganisationDateOfInception" name="OrganisationDateOfInception" value="@Model.Data.OrganisationDateOfInception" />
            <input type="hidden" id="OrganisationType" name="OrganisationType" value="@Model.Data.OrganisationType" />
            <input type="hidden" id="PublicSectorDataSource" name="PublicSectorDataSource" value="@Model.Data.PublicSectorDataSource" />
            <input type="hidden" id="Sector" name="Sector" value="@Model.Data.Sector" />
            <div class="form-group">
                <input class="button" type="submit" value="Find address" />
                <a class="button-link" href="@Url.Action("AddOrganisationAddress", new
                         {
                             Model.Data.OrganisationName,
                             Model.Data.OrganisationReferenceNumber,
                             Model.Data.OrganisationDateOfInception,
                             Model.Data.OrganisationType,
                             Model.Data.PublicSectorDataSource,
                             Model.Data.Sector
                         })">Enter address manually</a>
            </div>
        </form>

        
    </div>
</div>

@section breadcrumb {
    <div class="breadcrumbs">
        <a href="@Url.Action("SelectEmployer", "EmployerAccount")" class="link-back">Back</a>
    </div>
}

src/SFA.DAS.EAS.Web/Views/EmployerAccountOrganisation/ViewPublicSectorOrganisationSearchResults.cshtml
@using SFA.DAS.EAS.Domain
@using SFA.DAS.EAS.Domain.Models.Organisation
@model SFA.DAS.EAS.Web.OrchestratorResponse<SFA.DAS.EAS.Web.ViewModels.Organisation.PublicSectorOrganisationSearchResultsViewModel>
@{ViewBag.PageID = "page-extra-public-sector-organisation-search-results"; }
@{
    ViewBag.Title = "Public Sector Orgainsation Search Results";
    ViewBag.Section = "organisations";
    ViewBag.HideNav = "true";
}
<div class="grid-row">
    <div class="column-two-thirds">
        <h1 class="heading-xlarge">
            Public sector search results
        </h1>

        <form action="@Url.Action("AddOrganisation")" method="POST">
            @Html.AntiForgeryToken()
            @*<input type="hidden" id="hashedAccountId" name="hashedAccountId" value="@Model.Data.HashedAccountId" />*@
            <input type="hidden" id="OrganisationType" name="OrganisationType" value="@OrganisationType.PublicBodies" />
            <div class="search-field">
                <fieldset class="search-input">
                    <label for="org-search">
                        <span class="form-label-bold">Search results</span>
                    </label>
                    <input type="text" name="org-search" id="org-search" value="@Model.Data.SearchTerm" class="form-control">
                </fieldset>
                <fieldset class="search-submit">
                    <button type="submit" class="button">Search</button>
                </fieldset>
            </div>
        </form>
        @{
            <p>@Model.Data.Results.Data.Count results found.</p>
            <ol class="search-results">
                @foreach (var result in Model.Data.Results.Data)
                {
                    if (!result.AddedToAccount)
                    {
                        <li>
                            <form action="@Url.Action("FindAddress", "EmployerAccountOrganisation")" method="post">
                                <input type="hidden" id="OrganisationHashedId" name="OrganisationHashedId" value="@Model.Data.HashedAccountId" />
                                <input type="hidden" id="OrganisationDateOfInception" name="OrganisationDateOfInception" value="@result.DateOfInception" />
                                <input type="hidden" id="OrganisationReferenceNumber" name="OrganisationReferenceNumber" value="@result.ReferenceNumber" />
                                <input type="hidden" id="PublicSectorDataSource" name="PublicSectorDataSource" value="@result.PublicSectorDataSource" />
                                <input type="hidden" id="OrganisationType" name="OrganisationType" value="@OrganisationType.PublicBodies" />
                                <input type="hidden" id="Sector" name="Sector" value="@result.Sector" />
                                <input type="hidden" id="Status" name="Status" value="@result.Status" />
                                <input type="hidden" id="OrganisationName" name="OrganisationName" value="@result.Name" />
                                <input type="hidden" id="OrganisationAddress" name="OrganisationAddress" value="@result.Address" />
                                <button type="submit" class="link-button">@result.Name</button>
                            </form>


                        </li>
                    }
                    else
                    {
                        <li>@result.Name (Already added)</li>
                    }
                }
            </ol>
        }

        <h3 class="heading-small">Can't find your organisation?</h3>
        <p>You can <a href="@Url.Action("AddOtherOrganisationDetails")">add it manually here</a>.</p>

    </div>
</div>

@section breadcrumb {
    <div class="breadcrumbs">
        <ol role="navigation">
            <li><a href="@Url.Action("AddOrganisation", "EmployerAccountOrganisation")" class="back-link">Back</a></li>
        </ol>
    </div>
}