src/SFA.DAS.EAS.Web/Models/DeleteApprenticeshipConfirmationViewModel.cs
using FluentValidation.Attributes;
using SFA.DAS.EAS.Web.Validators;

namespace SFA.DAS.EAS.Web.Models
{
    [Validator(typeof(DeleteApprenticeshipConfirmationViewModelValidator))]
    public class DeleteApprenticeshipConfirmationViewModel
    {
        public string HashedAccountId { get; set; }
        public string HashedCommitmentId { get; set; }
        public string HashedApprenticeshipId { get; set; }
        public bool? DeleteConfirmed { get; set; }
        public string ApprenticeshipName { get; set; }
        public string DateOfBirth { get; set; }
    }
}

src/SFA.DAS.EAS.Web/ViewModels/AcknowledgementViewModel.cs
namespace SFA.DAS.EAS.Web.ViewModels
{
    public class AcknowledgementViewModel
    {
        public string HashedAccount { get; set; }

        public string HashedCommitmentId { get; set; }

        public string ProviderName { get; set; }

        public string LegalEntityName { get; set; }

        public string Message { get; set; }

        public LinkViewModel BackLink { get; set; }

        public AcknowledgementContent Content { get; set; }
    }

    public class LinkViewModel
    {
        public string Url { get; set; }

        public string  Text { get; set; }
    }

    public class AcknowledgementContent
    {
        public string Title { get; set; }

        public string Text { get; set; }
    }
}

src/SFA.DAS.EAS.Web/ViewModels/DeleteApprenticeshipConfirmationViewModel.cs
using FluentValidation.Attributes;
using SFA.DAS.EAS.Web.Validators;

namespace SFA.DAS.EAS.Web.ViewModels
{
    [Validator(typeof(DeleteApprenticeshipConfirmationViewModelValidator))]
    public class DeleteApprenticeshipConfirmationViewModel
    {
        public string HashedAccountId { get; set; }
        public string HashedCommitmentId { get; set; }
        public string HashedApprenticeshipId { get; set; }
        public bool? DeleteConfirmed { get; set; }
        public string ApprenticeshipName { get; set; }
        public string DateOfBirth { get; set; }
    }
}

src/SFA.DAS.EAS.Web/ViewModels/YourCohortsViewModel.cs
namespace SFA.DAS.EAS.Web.ViewModels
{
    public class YourCohortsViewModel
    {
        public int WaitingToBeSentCount { get; set; }

        public int ReadyForApprovalCount { get; set; }

        public int ReadyForReviewCount { get; set; }

        public int WithProviderCount { get; set; }
    }
}

src/SFA.DAS.EAS.Web/Controllers/EmployerCommitmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Newtonsoft.Json;

using SFA.DAS.EAS.Application;
using SFA.DAS.EAS.Domain.Interfaces;
using SFA.DAS.EAS.Domain.Models.UserProfile;
using SFA.DAS.EAS.Web.Authentication;
using SFA.DAS.EAS.Web.Enums;
using SFA.DAS.EAS.Web.Orchestrators;
using SFA.DAS.EAS.Web.Exceptions;
using SFA.DAS.EAS.Web.Extensions;
using SFA.DAS.EAS.Web.ViewModels;
using SFA.DAS.EmployerUsers.WebClientComponents;
using SFA.DAS.EAS.Web.Validators;
using FluentValidation.Mvc;
using FluentValidation;

namespace SFA.DAS.EAS.Web.Controllers
{

    [Authorize]
    [RoutePrefix("accounts/{hashedaccountId}/apprentices")]
    public class EmployerCommitmentsController : BaseController
    {
        private readonly EmployerCommitmentsOrchestrator _employerCommitmentsOrchestrator;

        private const string LastCohortPageSessionKey = "lastCohortPageSessionKey";

        public EmployerCommitmentsController(EmployerCommitmentsOrchestrator employerCommitmentsOrchestrator, IOwinWrapper owinWrapper,
            IFeatureToggle featureToggle, IMultiVariantTestingService multiVariantTestingService, ICookieStorageService<FlashMessageViewModel> flashMessage)
            : base(owinWrapper, featureToggle, multiVariantTestingService, flashMessage)
        {
            if (employerCommitmentsOrchestrator == null)
                throw new ArgumentNullException(nameof(employerCommitmentsOrchestrator));
            if (owinWrapper == null)
                throw new ArgumentNullException(nameof(owinWrapper));

            _employerCommitmentsOrchestrator = employerCommitmentsOrchestrator;
        }

        [HttpGet]
        [Route("home")]
        public async Task<ActionResult> Index(string hashedAccountId)
        {
            ViewBag.HashedAccountId = hashedAccountId;

            var response = await _employerCommitmentsOrchestrator.CheckAccountAuthorization(hashedAccountId, OwinWrapper.GetClaimValue(@"sub"));

            return View(response);
        }

        [HttpGet]
        [OutputCache(CacheProfile = "NoCache")]
        [Route("cohorts")]
        public async Task<ActionResult> YourCohorts(string hashedAccountId)
        {
            if (!await IsUserRoleAuthorized(hashedAccountId, Role.Owner, Role.Transactor))
                return View("AccessDenied");

            var model = await _employerCommitmentsOrchestrator.GetYourCohorts(hashedAccountId, OwinWrapper.GetClaimValue(@"sub"));

            SetFlashMessageOnModel(model);
            return View(model);
        }

        [HttpGet]
        [OutputCache(CacheProfile = "NoCache")]
        [Route("cohorts/new")]
        public async Task<ActionResult> WaitingToBeSent(string hashedAccountId)
        {
            if (!await IsUserRoleAuthorized(hashedAccountId, Role.Owner, Role.Transactor))
                return View("AccessDenied");

            var model = await _employerCommitmentsOrchestrator.GetAllWaitingToBeSent(hashedAccountId, OwinWrapper.GetClaimValue(@"sub"));
            SetFlashMessageOnModel(model);
            Session[LastCohortPageSessionKey] = RequestStatus.NewRequest;
            return View("RequestList", model);
        }

        [HttpGet]
        [Route("cohorts/approve")]
        public async Task<ActionResult> ReadyForApproval(string hashedAccountId)
        {
            if (!await IsUserRoleAuthorized(hashedAccountId, Role.Owner, Role.Transactor))
                return View("AccessDenied");

            var model = await _employerCommitmentsOrchestrator.GetAllReadyForApproval(hashedAccountId, OwinWrapper.GetClaimValue(@"sub"));
            SetFlashMessageOnModel(model);
            Session[LastCohortPageSessionKey] = RequestStatus.ReadyForApproval;
            return View("RequestList", model);
        }

        [HttpGet]
        [Route("cohorts/review")]
        public async Task<ActionResult> ReadyForReview(string hashedAccountId)
        {
            if (!await IsUserRoleAuthorized(hashedAccountId, Role.Owner, Role.Transactor ))
                return View("AccessDenied");

            var model = await _employerCommitmentsOrchestrator.GetAllReadyForReview(hashedAccountId, OwinWrapper.GetClaimValue(@"sub"));
            SetFlashMessageOnModel(model);
            Session[LastCohortPageSessionKey] = RequestStatus.ReadyForReview;
            return View("RequestList", model);
        }

        [HttpGet]
        [Route("cohorts/provider")]
        public async Task<ActionResult> WithProvider(string hashedAccountId)
        {
            if (!await IsUserRoleAuthorized(hashedAccountId, Role.Owner, Role.Transactor))
                return View("AccessDenied");

            var model = await _employerCommitmentsOrchestrator.GetAllWithProvider(hashedAccountId, OwinWrapper.GetClaimValue(@"sub"));
            return View("RequestList", model);
        }

        [HttpGet]
        [Route("Inform")]
        public async Task<ActionResult> Inform(string hashedAccountId)
        {
            var response = await _employerCommitmentsOrchestrator.GetInform(hashedAccountId, OwinWrapper.GetClaimValue(@"sub"));

            return View(response);
        }

        [HttpGet]
        [Route("legalEntity/create")]
        public async Task<ActionResult> SelectLegalEntity(string hashedAccountId, string cohortRef = "")
        {
            if (!await IsUserRoleAuthorized(hashedAccountId, Role.Owner, Role.Transactor))
                return View("AccessDenied");

            var response = await _employerCommitmentsOrchestrator
                .GetLegalEntities(hashedAccountId, cohortRef, OwinWrapper.GetClaimValue(@"sub"));

            return View(response);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("legalEntity/create")]
        public async Task<ActionResult> SetLegalEntity(string hashedAccountId, SelectLegalEntityViewModel selectedLegalEntity)
        {
            if (!ModelState.IsValid)
            {
                var response = await _employerCommitmentsOrchestrator.GetLegalEntities(hashedAccountId, selectedLegalEntity.CohortRef, OwinWrapper.GetClaimValue(@"sub"));

                return View("SelectLegalEntity", response);
            }

            var agreement = await _employerCommitmentsOrchestrator.GetLegalEntitySignedAgreementViewModel(hashedAccountId,
                selectedLegalEntity.LegalEntityCode, selectedLegalEntity.CohortRef);

            if (agreement.Data.HasSignedAgreement)
            {
                return RedirectToAction("SearchProvider", selectedLegalEntity);
            }
            else
            {
                return RedirectToAction("AgreementNotSigned", agreement.Data);
            }
            
        }

        [HttpGet]
        [Route("provider/create")]
        public async Task<ActionResult> SearchProvider(string hashedAccountId, string legalEntityCode, string cohortRef)
        {
            if (!await IsUserRoleAuthorized(hashedAccountId, Role.Owner, Role.Transactor))
                return View("AccessDenied");

            if (string.IsNullOrWhiteSpace(legalEntityCode) || string.IsNullOrWhiteSpace(cohortRef))
            {
                return RedirectToAction("Inform", new {hashedAccountId});
            }

            var response = await _employerCommitmentsOrchestrator.GetProviderSearch(hashedAccountId, OwinWrapper.GetClaimValue(@"sub"), legalEntityCode, cohortRef);

            return View(response);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("provider/create")]
        public async Task<ActionResult> SelectProvider(string hashedAccountId, [System.Web.Http.FromUri] [CustomizeValidator(RuleSet = "Request")] SelectProviderViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                var defaultViewModel = await _employerCommitmentsOrchestrator.GetProviderSearch(hashedAccountId, OwinWrapper.GetClaimValue(@"sub"), viewModel.LegalEntityCode, viewModel.CohortRef);
                
                return View("SearchProvider", defaultViewModel);
            }

            var response = await _employerCommitmentsOrchestrator.GetProvider(hashedAccountId, OwinWrapper.GetClaimValue(@"sub"), viewModel);

            if (response.Data.Provider == null)
            {
                var defaultViewModel = await _employerCommitmentsOrchestrator.GetProviderSearch(hashedAccountId, OwinWrapper.GetClaimValue(@"sub"), viewModel.LegalEntityCode, viewModel.CohortRef);
                defaultViewModel.Data.NotFound = true;

                RevalidateModel(defaultViewModel);

                return View("SearchProvider", defaultViewModel);
            }

            return View(response);
        }

        private void RevalidateModel(OrchestratorResponse<SelectProviderViewModel> defaultViewModel)
        {
            var validator = new SelectProviderViewModelValidator();
            var results = validator.Validate(defaultViewModel.Data, ruleSet: "SearchResult");
            
            results.AddToModelState(ModelState, null);
        }

        [HttpGet]
        [Route("confirmProvider/create")]
        public async Task<ActionResult> ConfirmProvider(string hashedAccountId)
        {
            if (!await IsUserRoleAuthorized(hashedAccountId, Role.Owner, Role.Transactor))
                return View("AccessDenied");

            return RedirectToAction("Inform", new { hashedAccountId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("confirmProvider/create")]
        public async Task<ActionResult> ConfirmProvider(string hashedAccountId, [System.Web.Http.FromUri]ConfirmProviderViewModel viewModelModel)
        {
            if (!ModelState.IsValid)
            {
                if (viewModelModel.Confirmation == null)
                {

src/SFA.DAS.EAS.Web/Views/EmployerCommitments/Approved.cshtml
@model SFA.DAS.EAS.Web.OrchestratorResponse<SFA.DAS.EAS.Web.ViewModels.AcknowledgementViewModel>

@{
    ViewBag.Title = "Cohort approved";
    ViewBag.PageID = "cohort-approved";
}


<div class="grid-row">
    <div class="column-full">
        <div class="govuk-box-highlight green-box">
            <h1 class="heading-xlarge" id="changeHeadline">
                Cohort approved
            </h1>
        </div>
    </div>
</div>

<div class="grid-row">
    <div class="column-full">

        <table class="instructionSent">
            <tbody>
                <tr>
                    <td>Cohort reference</td>
                    <td class="strong">@Model.Data.HashedCommitmentId</td>
                </tr>
                <tr>
                    <td>Provider </td>
                    <td class="strong">@Model.Data.ProviderName</td>
                </tr>
                <tr>
                    <td>Approved by</td>
                    <td class="strong">@Model.Data.LegalEntityName</td>
                </tr>                
            </tbody>
        </table>


        <h2 class="heading-medium">What happens next?</h2>
        <p id="changeMainCopy">
            Your cohort has been approved. To view or update apprentice details or stop payments for any apprentices in this cohort you will need to 
            <a href="@Url.Action("ListAll" ,"EmployerManageApprentices")">manage your apprentices</a>
        </p>

        @if (!string.IsNullOrEmpty(Model.Data.BackLink?.Url))
        {
            <p>
                <a href="@Model.Data.BackLink.Url" aria-label="@Model.Data.BackLink.Text">@Model.Data.BackLink.Text</a>
            </p>
        }
    </div>
</div>

<div class="grid-row">
    <div class="column-full">
        <aside>
            <div class="panel panel-filled">
                <h2 class="heading-medium">Help us improve this section</h2>
                <p>Take a 3 minute survey about adding apprentices so that we can improve the service.</p>
                <a href=" https://www.surveymonkey.co.uk/r/viewlevy" target="_blank" class="button" title="Take the survey" aria-label="Take the survey">Take the survey</a>
            </div>
        </aside>
    </div>
</div>


@section breadcrumb {
    <div class="breadcrumbs">
        <a href="@Url.Action("Index", "EmployerCommitments")" aria-label="Back to Apprentices" class="back-link">Back to Apprentices</a>
    </div>
}

src/SFA.DAS.EAS.Web/Views/EmployerCommitments/ChoosePath.cshtml
@using SFA.DAS.EAS.Web
@using SFA.DAS.EAS.Web.Extensions

@model OrchestratorResponse<SFA.DAS.EAS.Web.ViewModels.CreateCommitmentViewModel>

@{
    ViewBag.Title = "Start adding apprentices";
    ViewBag.PageID = "choose-add-path";
}

@*@section pageSpecificJS {
    @Scripts.Render("~/bundles/jqueryvalcustom")
}*@

<div class="grid-row">
    <div class="column-two-thirds">
        <form method="POST" action="@Url.Action("CreateCommitment")">
            @Html.AntiForgeryToken()
            @Html.Partial("ValidationSummary", Html.ViewData.ModelState)

            <h1 class="heading-xlarge">Start adding apprentices</h1>
            <p class="lede">You can start adding details of your apprentices or ask your training provider to add them for you.</p>
            <p class="lede">If you ask your training provider to add them, you need to check and agree the details before any payments are made.</p>
            <fieldset role="radiogroup" aria-required="true">
                <legend class="visuallyhidden">Choose provider to enter details</legend>
                <div class="form-error-group form-group @Html.AddClassIfPropertyInError("SelectedRoute", "error")">
                 
                        @Html.ValidationMessage("SelectedRoute", "Please choose an option", new { id = "error-message-SelectedRoute" })
                   
                    <label class="block-label selection-button-radio" for="SelectedRoute-Employer">
                        @Html.RadioButton("SelectedRoute", "employer", new { id = "SelectedRoute-Employer" })
                        I will add apprentices
                    </label>
                    <label class="block-label selection-button-radio" for="SelectedRoute-Provider">
                        @Html.RadioButton("SelectedRoute", "provider", new { id = "SelectedRoute-Provider" })
                        I would like my provider to add apprentices
                    </label>
                </div>
            </fieldset>
            @Html.Hidden("CohortRef", Model.Data.CohortRef)
            @Html.Hidden("LegalEntityCode", Model.Data.LegalEntityCode)
            @Html.Hidden("LegalEntityName", Model.Data.LegalEntityName)
            @Html.Hidden("LegalEntityAddress", Model.Data.LegalEntityAddress)
            @Html.Hidden("LegalEntitySource", Model.Data.LegalEntitySource)
            @Html.Hidden("ProviderId", Model.Data.ProviderId)
            @Html.Hidden("ProviderName", Model.Data.ProviderName)
            <button type="submit" class="button">Continue</button>
        </form>
    </div>
    <div class="column-one-third"></div>
</div>

@section breadcrumb {
    <div class="breadcrumbs">
        <a href="@Url.Action("Index", "EmployerCommitments")" aria-label="Back to Apprentices" class="back-link">Back to Apprentices</a>   
    </div>
}

src/SFA.DAS.EAS.Web/Views/EmployerCommitments/DeleteCohort.cshtml
@using SFA.DAS.EAS.Web.Extensions
@model SFA.DAS.EAS.Web.OrchestratorResponse<SFA.DAS.EAS.Web.ViewModels.DeleteCommitmentViewModel>

@{
    ViewBag.Title = "Confirm Delete Cohort";
    ViewBag.PageId = "confirm-delete-cohort";
}

<div class="grid-row" id="confirm-delete">
    <div class="column-two-thirds">

        <form action="@Url.Action("DeleteCohort")" method="POST">
            @Html.AntiForgeryToken()
            @Html.Partial("ValidationSummary", Html.ViewData.ModelState)

            <h1 class="heading-xlarge">Confirm cohort deletion</h1>
            <p>You are about to delete the following cohort:</p>

            <table id="delete-cohort-summary">
                <tr>
                    <td>Provider</td>
                    <td class="strong">@Model.Data.ProviderName</td>
                </tr>
                <tr>
                    <td>Cohort reference</td>
                    <td class="strong">@Model.Data.HashedCommitmentId</td>
                </tr>
                <tr>
                    <td>Number of apprentices</td>
                    <td class="strong">@Model.Data.NumberOfApprenticeships</td>
                </tr>
                <tr>
                    <td>Apprenticeships</td>
                    @if (!Model.Data.ProgrammeSummaries.Any())
                    {
                        <td class="strong">0</td>
                    }
                    else
                    {
                        <td class="strong">
                            @Model.Data.ProgrammeSummaries.First()
                        </td>
                    }
                </tr>
                @foreach (var programSummary in Model.Data.ProgrammeSummaries.Skip(1))
                {
                    <tr>
                        <td></td>
                        <td class="strong">@programSummary</td>
                    </tr>

                }
            </table>

            <h2 class="heading-medium">
                Are you sure you want to delete this entire cohort and all the apprentices in it?
            </h2>

        <div class="form-error-group form-group @Html.AddClassIfPropertyInError("DeleteConfirmed", "error")">
                <div>
                    @Html.ValidationMessage("DeleteConfirmed", "Please choose an option", new { id = "error-message-" + "DeleteConfirmed" })
                </div>
                <fieldset>
                    <legend class="visually-hidden">
                        Are you sure you want to delete this entire cohort and all the apprentices in it?
                    </legend>

                    <label class="block-label selection-button-radio" for="@Html.IdFor(m => m.Data.DeleteConfirmed)-True">
                        @Html.RadioButton("DeleteConfirmed", true, Model.Data.DeleteConfirmed == false, new { @id = Html.IdFor(m => m.Data.DeleteConfirmed) + "-True" })
                        Yes, delete cohort
                    </label>
                    <label class="block-label selection-button-radio" for="@Html.IdFor(m => m.Data.DeleteConfirmed)-False">
                        @Html.RadioButton("DeleteConfirmed", false, Model.Data.DeleteConfirmed == true, new { @id = Html.IdFor(m => m.Data.DeleteConfirmed) + "-False" })
                        No, don't delete cohort
                    </label>
                </fieldset>
            </div>
            <button type="submit" class="button">Continue</button>
        </form>

    </div>
</div>

@section breadcrumb {
    <div class="breadcrumbs">
        <a href="@Url.Action("Details", "EmployerCommitments", new { Model.Data.HashedAccountId, Model.Data.HashedCommitmentId })" aria-label="Back to Cohort" class="back-link">
            Back to Cohort
        </a>
    </div>
}

src/SFA.DAS.EAS.Web/Views/EmployerCommitments/EditApprenticeshipEntry.cshtml
@using SFA.DAS.EAS.Web
@model OrchestratorResponse<SFA.DAS.EAS.Web.ViewModels.ExtendedApprenticeshipViewModel>

@{
    ViewBag.Title = "Edit an apprentice";
    ViewBag.PageID = "edit-apprentice";
}

@section pageSpecificJS {
    @Scripts.Render("~/bundles/apprentice")
    @Scripts.Render("~/bundles/characterLimitation")

}

<div class="grid-row">
    <div class="column-two-thirds">
        <form method="POST" action="@Url.Action("EditApprenticeship")" novalidate="novalidate">
            @Html.AntiForgeryToken()

            <h1 class="heading-xlarge">Edit apprentice details</h1>
            <div class="panel panel-border-wide">
                <p>
                    You’ll only be able to authorise payments for this apprentice once all the fields have been completed – either by yourself or your training provider.
                </p>
            </div>
 
            <hr />

            @Html.Partial("EditApprenticeship", Model.Data)
          

            <div class="form-group">
                <hr />
                <div class="grey-background">
                    <p class="form-label-bold">End-point assessments</p>
                    <p>If you've chosen an apprenticeship standard, we'll ask you to confirm the <a href="https://www.gov.uk/government/publications/using-the-register-of-apprentice-assessment-organisations" target="_blank" title="Opens in a new window" rel="external">apprentice assessment organisation</a> for this apprentice. We'll do this before the end of the apprenticeship.</p>
                    <p>
                        Apprenticeship frameworks have different assessment arrangements and don't need end-point assessments.
                    </p>
                </div>
            </div>

            @Html.Hidden("ULN", Model.Data.Apprenticeship.ULN)
            @Html.Hidden("AgreementStatus", Model.Data.Apprenticeship.AgreementStatus)
            @Html.Hidden("ProviderRef", Model.Data.Apprenticeship.ProviderRef)

            <button type="submit" class="button">Save</button>
            <a class="button delete-button" href="@Url.Action("DeleteApprenticeshipConfirmation", new { Model.Data.Apprenticeship.HashedCommitmentId, Model.Data.Apprenticeship.HashedApprenticeshipId })" aria-label="Cancel">Delete</a>
            <a class="links" href="@Url.Action("Details", new { hashedAccountId = Model.Data.Apprenticeship.HashedAccountId, hashedCommitmentId = Model.Data.Apprenticeship.HashedCommitmentId })" aria-label="Cancel">Cancel</a>
            
        </form>
    </div>
</div>


@section breadcrumb {
    <div class="breadcrumbs">
        <a href="@Url.Action("Index", "EmployerCommitments")" aria-label="Back to Apprentices" class="back-link">Back to Apprentices</a>
    </div>
}

src/SFA.DAS.EAS.Web/Views/EmployerCommitments/RequestList.cshtml
@model SFA.DAS.EAS.Web.OrchestratorResponse<SFA.DAS.EAS.Web.ViewModels.CommitmentListViewModel>

@{
    ViewBag.Title = Model.Data.PageTitle;
    ViewBag.PageId = Model.Data.PageId;
}

<div class="grid-row">
    <div class="column-full">
        <h1 class="heading-xlarge">@Model.Data.PageHeading</h1>

        <p class="dynamic-heading">@Html.Raw(Model.Data.PageHeading2)</p>

        <table class="tableResponsive to-be-sent-list">
            <thead>
            <tr>
                <th>Provider</th>
                <th>Cohort reference</th>
                <th>Last message</th>
                <th></th>

            </tr>
            </thead>
            <tbody>
            @foreach (var commitment in Model.Data.Commitments)
            {
                <tr>
                    <td>
                        @commitment.ProviderName &nbsp;
                    </td>
                    <td>
                        @commitment.HashedCommitmentId &nbsp;
                    </td>
                    <td>
                        @commitment.LatestMessage &nbsp;
                    </td>
                    <td>
                        @if (commitment.ShowViewLink)
                        {
                            <a href="@Url.Action("Details", new { commitment.HashedCommitmentId })" title="View cohort" aria-label="View cohort">View</a>
                        }
                    </td>
                </tr>
            }
            </tbody>
        </table>


    </div>
</div>

@section breadcrumb {
    <div class="breadcrumbs">
        <a href="@Url.Action("YourCohorts", "EmployerCommitments")" aria-label="Back to Apprentices" class="back-link">Back to Apprentices</a>
    </div>
}

src/SFA.DAS.EAS.Web/Views/EmployerCommitments/SearchProvider.cshtml
@using SFA.DAS.EAS.Web
@using SFA.DAS.EAS.Web.Extensions

@model OrchestratorResponse<SFA.DAS.EAS.Web.ViewModels.SelectProviderViewModel>

@{
    ViewBag.Title = "Add training provider details";
    ViewBag.PageID = "add-provider-reference";
}

@*@section pageSpecificJS {
    @Scripts.Render("~/bundles/jqueryvalcustom")
}*@

<form method="POST" action="@Url.Action("SelectProvider")">

    <div class="grid-row">
        <div class="column-two-thirds">
            @Html.Partial("ValidationSummary", Html.ViewData.ModelState)
            <h1 class="heading-xlarge">Add training provider details</h1>

            @Html.AntiForgeryToken()
            
            <div class="form-error-group form-group @Html.AddClassIfPropertyInError("ProviderId", "error") @Html.AddClassIfPropertyInError("NotFound", "error")">
                @Html.LabelFor(m => m.Data.ProviderId, "UK Provider Reference Number", new { @class = "form-label-bold" })

                @Html.ValidationMessage("ProviderId", "Number not recognised. Check the number you've entered is correct or contact your training provider for help.", new { id = "error-message-ProviderId" })
                @Html.ValidationMessage("NotFound", "Number not recognised. Check the number you've entered is correct or contact your training provider for help.", new { id = "error-message-NotFound" })
           
                @Html.TextBox("ProviderId", Model.Data.ProviderId, new { @class = "form-control trainingProvider", aria_required = "true", aria_labelledby = "ProviderId" })
            </div>

            <details class="ukprn-help">
                <summary><span class="summary">What is a UK Provider Reference Number?</span></summary>
                <div class="panel panel-border-narrow" role="note" aria-label="UKPRN help">
                    <p>
                        A UK Provider Reference Number (UKPRN) is a unique, 8-digit number that identifies a training provider. Your training provider can tell you their UKPRN.
                    </p>
                </div>
            </details>


            <button type="submit" class="button">Continue</button>

            @Html.Hidden("LegalEntityCode", Model.Data.LegalEntityCode)
            @Html.Hidden("CohortRef", Model.Data.CohortRef)
        </div>
    </div>
</form>


@section breadcrumb {
    <div class="breadcrumbs">
        <a href="@Url.Action("Index", "EmployerCommitments")" aria-label="Back to Apprentices" class="back-link">Back to Apprentices</a>
    </div>
}