src/SFA.DAS.EAS.Web/Controllers/EmployerTeamController.cs
using System;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using SFA.DAS.EAS.Application;
using SFA.DAS.EAS.Domain.Interfaces;
using SFA.DAS.EAS.Web.Authentication;
using SFA.DAS.EAS.Web.Orchestrators;
using SFA.DAS.EAS.Web.ViewModels;

namespace SFA.DAS.EAS.Web.Controllers
{
    [Authorize]
    [RoutePrefix("accounts/{HashedAccountId}/teams")]
    public class EmployerTeamController : BaseController
    {
        private readonly EmployerTeamOrchestrator _employerTeamOrchestrator;

        public EmployerTeamController(IOwinWrapper owinWrapper, EmployerTeamOrchestrator employerTeamOrchestrator, 
            IFeatureToggle featureToggle, IMultiVariantTestingService multiVariantTestingService, ICookieStorageService<FlashMessageViewModel> flashMessage) 
            : base(owinWrapper, featureToggle, multiVariantTestingService, flashMessage)
        {
            _employerTeamOrchestrator = employerTeamOrchestrator;
        }

        [HttpGet]
        [Route]
        public async Task<ActionResult> Index(string hashedAccountId)
        {
            var userIdClaim = OwinWrapper.GetClaimValue(@"sub");

            var response = await _employerTeamOrchestrator.GetAccount(hashedAccountId, userIdClaim);

            var flashMessage = GetFlashMessageViewModelFromCookie();

            if (flashMessage!=null)
            {
                response.FlashMessage = flashMessage;
                response.Data.EmployerAccountType = flashMessage.HiddenFlashMessageInformation;
            }

            return View(response);
        }

        [HttpGet]
        [Route("view")]
        public async Task<ActionResult> ViewTeam(string hashedAccountId)
        {
            
            var response = await _employerTeamOrchestrator.GetTeamMembers(hashedAccountId, OwinWrapper.GetClaimValue(@"sub"));

            var flashMessage = GetFlashMessageViewModelFromCookie();
            if (flashMessage != null)
            {
                response.FlashMessage = flashMessage;
            }

            return View(response);
        }

        [HttpGet]
        [Route("invite")]
        public async Task<ActionResult> Invite(string hashedAccountId)
        {
            var response = await _employerTeamOrchestrator.GetNewInvitation(hashedAccountId, OwinWrapper.GetClaimValue(@"sub"));

            return View(response);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("invite")]
        public async Task<ActionResult> Invite(InviteTeamMemberViewModel model)
        {
            var response = await _employerTeamOrchestrator.InviteTeamMember(model, OwinWrapper.GetClaimValue(@"sub"));

            if (response.Status == HttpStatusCode.OK)
            {
                var flashMessage = new FlashMessageViewModel
                {
                    HiddenFlashMessageInformation = "page-invite-team-member-sent",
                    Severity = FlashMessageSeverityLevel.Success,
                    Headline = "Invitation sent",
                    Message = $"You've sent an invitation to <strong>{model.Email}</strong>"
                };
                AddFlashMessageToCookie(flashMessage);

                return RedirectToAction("ViewTeam");
            }
                
           
            model.ErrorDictionary = response.FlashMessage.ErrorMessages; 
            var errorResponse = new OrchestratorResponse<InviteTeamMemberViewModel>
            {
                Data = model,
                FlashMessage = response.FlashMessage,
            };

            return View(errorResponse);
        }
        
        [HttpGet]
        [Route("{invitationId}/cancel")]
        public async Task<ActionResult> Cancel(string email, string invitationId, string hashedAccountId)
        {
            var invitation = await _employerTeamOrchestrator.GetInvitation(invitationId);

            return View(invitation);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("{invitationId}/cancel")]
        public async Task<ActionResult> Cancel(string invitationId, string email, string hashedAccountId, int cancel)
        {
            if (cancel != 1)
                return RedirectToAction("ViewTeam", new { HashedAccountId = hashedAccountId });

            var response =  await _employerTeamOrchestrator.Cancel(email, hashedAccountId, OwinWrapper.GetClaimValue(@"sub"));

            return View("ViewTeam", response);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("resend")]
        public async Task<ActionResult> Resend(string hashedAccountId, string email)
        {
            var response = await _employerTeamOrchestrator.Resend(email, hashedAccountId, OwinWrapper.GetClaimValue(@"sub"));
            
            return View("ViewTeam", response);
        }

        [HttpGet]
        [Route("{email}/remove/")]
        public async Task<ActionResult> Remove(string hashedAccountId, string email)
        {
            var response = await _employerTeamOrchestrator.Review(hashedAccountId, email);

            return View(response);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("{email}/remove")]
        public async Task<ActionResult> Remove(long userId, string hashedAccountId, string email, int remove)
        {
            Exception exception;
            HttpStatusCode httpStatusCode;
            
            try
            {
                if (remove != 1)
                    return RedirectToAction("ViewTeam", new { HashedAccountId = hashedAccountId });

                var response = await _employerTeamOrchestrator.Remove(userId, hashedAccountId, OwinWrapper.GetClaimValue(@"sub"));
                
                return View("ViewTeam", response);
            }
            catch (InvalidRequestException e)
            {
                httpStatusCode = HttpStatusCode.BadRequest;
                exception = e;
            }
            catch (UnauthorizedAccessException e)
            {
                httpStatusCode = HttpStatusCode.Unauthorized;
                exception = e;
            }

            var errorResponse = await _employerTeamOrchestrator.Review(hashedAccountId, email);
            errorResponse.Status = httpStatusCode;
            errorResponse.Exception = exception;

            return View(errorResponse);
        }

        [HttpGet]
        [Route("{email}/role/change")]
        public async Task<ActionResult> ChangeRole(string hashedAccountId, string email)
        {
            var teamMember = await _employerTeamOrchestrator.GetTeamMember(hashedAccountId, email, OwinWrapper.GetClaimValue(@"sub"));

            return View(teamMember);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("{email}/role/change")]
        public async Task<ActionResult> ChangeRole(string hashedAccountId, string email, short role)
        {
            var response = await _employerTeamOrchestrator.ChangeRole(hashedAccountId, email, role, OwinWrapper.GetClaimValue(@"sub"));

            if (response.Status == HttpStatusCode.OK)
            {
                return View("ViewTeam", response);
            }
            
            var teamMemberResponse = await _employerTeamOrchestrator.GetTeamMember(hashedAccountId, email, OwinWrapper.GetClaimValue(@"sub"));

            //We have to override flash message as the change role view has different model to view team view
            teamMemberResponse.FlashMessage = response.FlashMessage;
            teamMemberResponse.Exception = response.Exception;

            return View(teamMemberResponse);
        }

        [HttpGet]
        [Route("{email}/review/")]
        public async Task<ActionResult> Review(string hashedAccountId, string email)
        {
            var invitation = await _employerTeamOrchestrator.GetTeamMember(hashedAccountId, email, OwinWrapper.GetClaimValue(@"sub"));

            return View(invitation);
        }
    }
}

src/SFA.DAS.EAS.Web/Views/EmployerTeam/Cancel.cshtml
@using SFA.DAS.EAS.Domain
@using SFA.DAS.EAS.Web

@model OrchestratorResponse<SFA.DAS.EAS.Domain.Models.AccountTeam.InvitationView>

@{
    ViewBag.PageID = "page-team-member-cancel-invite";
    ViewBag.Title = "Cancel invitation";
    ViewBag.Section = "team";
}

<div class="grid-row">
    <div class="column-two-thirds">
        <h1 class="heading-xlarge">Cancel invitation</h1>
        <p class="lede">Are you sure you want to cancel @Model.Data.Name's invitation?</p>
        <div class="form-group">
            <form action="@Url.Action("Cancel")" method="POST">
                @Html.AntiForgeryToken()
                <input type="hidden" id="cancel" name="cancel" value="1" />
                <input type="hidden" id="Email" name="Email" value="@Model.Data.Email" />
                <button type="submit" class="button" id="cancel_invitation">Yes, cancel invitation</button>
            </form>
            <a href="@Url.Action("Viewteam", "EmployerTeam")" class="button button-link">No, don't cancel invitation</a>
        </div>
    </div>
</div>
@section breadcrumb {
    <div class="breadcrumbs">
        <a href="@Url.Action("ViewTeam", "EmployerTeam")", class="back-link">Back to your team</a>
    </div>
}

src/SFA.DAS.EAS.Web/Views/EmployerTeam/ChangeRole.cshtml
@using SFA.DAS.EAS.Domain
@using SFA.DAS.EAS.Domain.Models.UserProfile
@using SFA.DAS.EAS.Web

@model OrchestratorResponse<SFA.DAS.EAS.Domain.Models.AccountTeam.TeamMember>

@{
    ViewBag.PageID = "page-team-member-change-role";
    var name = Model.Data.Name ?? Model.Data.Email;
    ViewBag.Title = name;
    ViewBag.Section = "team";
    var errorMessage = string.Empty;

}

@if (!ViewContext.ViewData.ModelState.IsValid)
{
    foreach (var state in ViewContext.ViewData.ModelState.Values)
    {
        foreach (var error in state.Errors)
        {
            errorMessage = error.ErrorMessage;
        }
    }

    <div class="error-summary" role="group" aria-labelledby="error-summary-heading" tabindex="-1">
        <h1 class="heading-medium error-summary-heading" id="error-summary-heading">
            Errors to fix
        </h1>
        <ul class="error-summary-list">
            <li><a href="#change-role-selection">@errorMessage</a></li>
        </ul>
    </div>

}


<div class="grid-row">
    <div class="column-two-thirds">
        <h1 class="heading-xlarge">@name</h1>
        <p class="lede">Choose what you allow this team member to do.</p>
       
        <form method="POST" action="@Url.Action("ChangeRole")">
            @Html.AntiForgeryToken()
            <div class="form-group @(!ViewContext.ViewData.ModelState.IsValid ? "error" : "")">
                <fieldset>
                    <legend id="change-role-selection">
                        <span class="vh">Select a role for @name</span>
                        @if (!string.IsNullOrWhiteSpace(errorMessage))
                        {
                            <span class="error-message">@errorMessage</span>
                        }
                    </legend>
                    <label class="block-label" for="radio1">
                        <input id="radio1" type="radio" name="Role" value="3" @(Model.Data.Role == Role.Viewer ? "checked" : "") />
                        @(RoleStrings.GetRoleDescription(Role.Viewer))
                    </label>
                    <label class="block-label" for="radio2">
                        <input id="radio2" type="radio" name="Role" value="2" @(Model.Data.Role == Role.Transactor ? "checked" : "") />
                        @(RoleStrings.GetRoleDescription(Role.Transactor))
                    </label>
                    <label class="block-label" for="radio3">
                        <input id="radio3" type="radio" name="Role" value="1" @(Model.Data.Role == Role.Owner ? "checked" : "") />
                        @(RoleStrings.GetRoleDescription(Role.Owner))
                    </label>
                    <input type="hidden" id="Email" name="Email" value="@Model.Data.Email" />
                </fieldset>
            </div>
            <button type="submit" class="button" id="update">Update</button>
        </form>
    </div>
</div>

@section breadcrumb {
    <div class="breadcrumbs">
        <a href="@Url.Action("ViewTeam", "EmployerTeam")", class="back-link">Back to your team</a>
    </div>
}

src/SFA.DAS.EAS.Web/Views/EmployerTeam/Index.cshtml
@using SFA.DAS.EAS.Web
@using SFA.DAS.EAS.Domain.Models.UserProfile

@model OrchestratorResponse<SFA.DAS.EAS.Web.ViewModels.AccountDashboardViewModel>

@{
    ViewBag.Title = "Home";
    ViewBag.Section = "home";
    ViewBag.PageID = "page-company-homepage";

    if (!string.IsNullOrEmpty(Model.Data.EmployerAccountType))
    {
        ViewBag.PageID = $"page-employer-account-created-{Model.Data.EmployerAccountType}";
    }
}


<h1 class="heading-xlarge heading-dashboard" id="company-Name">@Model.Data.Account.Name</h1>

<div class="grid-row page-dashboard">
    <div class="column-two-thirds">
     
        <div class="grid-row">
            <div class="column-half">
                <h2 class="heading-medium">
                    <a href="@Url.Action("ViewTeam")">Your team</a>
                </h2>
                <p>Control what your team can do and invite new team members.</p>

                <h2 class="heading-medium">
                    <a href="@Url.Action("Index", "EmployerAgreement")">Your organisations and agreements</a>
                </h2>
                <p>Add your organisations that will make contracts with training providers.</p>

                <h2 class="heading-medium">
                    <a href="@Url.Action("Index", "EmployerCommitments")">Apprentices</a>
                </h2>
                <p>Add apprentices, update details of existing apprentices and authorise payments to training providers.</p>

            </div>
            <div class="column-half">
                <h2 class="heading-medium">
                    <a href="@Url.Action("Index", "EmployerAccountTransactions")">Finance</a>
                </h2>
                <p>View your financial transactions.</p>
   
                <h2 class="heading-medium">
                    <a href="@Url.Action("Index", "EmployerAccountPaye")">PAYE schemes</a>
                </h2>
                <p>Add or remove <abbr title="Pay as your earn">PAYE</abbr> schemes.</p>
          
                <h2 class="heading-medium">
                    <a href="https://findapprenticeshiptraining.sfa.bis.gov.uk/" target="_blank" rel="external">Find apprenticeship training</a>
                </h2>
                <p>Search for apprenticeships and see details of approved providers who can deliver the training.</p>

            </div>

        </div>
   
           
        <div class="grid-row">
            <div class="column-full">
                <div class="panel panel-filled">
                    <h3 class="heading-medium">Help us improve this service</h3>
                    <p><a href="https://www.surveymonkey.co.uk/r/2JPLQ9T" target="_blank">Take our 3 minute survey</a> so that we can improve this service.</p>
                    <p><a href="https://www.surveymonkey.co.uk/r/2JPLQ9T" target="_blank" class="button">Take the survey <span class="vh">so that we can improve the service</span></a></p>
                </div>
            </div>
        </div>
        </div>
    <div class="column-one-third">
       
        @if (Model.Data.RequiresAgreementSigning > 0)
        {
            <section>
                <div class="panel alert-default">
                    <h3 class="heading-small">Spending not enabled (@Model.Data.RequiresAgreementSigning)</h3>

                    @if (Model.Data.UserRole == Role.Owner)
                    {
                        <p>You need to <a href="@Url.Action("Index", "EmployerAgreement")">accept an agreement</a> to enable your organisations to spend funds.</p>
                    }

                    @if (Model.Data.UserRole == Role.Transactor)
                    {
                        <p>An agreement needs to be accepted to enable your organisations to spend funds. <a href="@Url.Action("Index", "EmployerAgreement")">View this agreement</a>.</p>
                    }
              
                </div>
            </section>
        }
       
    </div>
</div>

src/SFA.DAS.EAS.Web/Views/EmployerTeam/Invite.cshtml
@using SFA.DAS.EAS.Domain
@using SFA.DAS.EAS.Domain.Models.UserProfile
@using SFA.DAS.EAS.Web

@model OrchestratorResponse<SFA.DAS.EAS.Web.ViewModels.InviteTeamMemberViewModel>

@{
    ViewBag.PageID = "page-invite-team-member";
    ViewBag.Title = "Create invitation";
    ViewBag.Section = "team";
}

        <div class="grid-row">
            <div class="column-two-thirds">
                <h1 class="heading-xlarge">
                    Create invitation
                </h1>
                <p class="lede">Invite somebody to access this account.</p>
                <form method="POST" action="@Url.Action("Invite")">
                    @Html.AntiForgeryToken()
                    <div class="form-group @(!string.IsNullOrEmpty(Model.Data.EmailError) || !string.IsNullOrEmpty(Model.Data.ExistingMemberError) ? "error" : "")">

                        <label for="Email">
                            <span class="form-label-bold">Email</span>
                            <span class="form-hint">An invitation will be sent to this email address</span>
                            @if (!string.IsNullOrEmpty(Model.Data.EmailError))
                            {
                                <span class="error-message" id="error-message-email">@Model.Data.EmailError</span>
                            }
                            @if (!string.IsNullOrEmpty(Model.Data.ExistingMemberError))
                            {
                                <span class="error-message" id="error-message-email">@Model.Data.ExistingMemberError</span>
                            }
                        </label>
                        <input class="form-control form-control-3-4" id="Email" name="Email" type="text"
                               @(!string.IsNullOrEmpty(Model.Data.EmailError) || !string.IsNullOrEmpty(Model.Data.ExistingMemberError) ? " aria-describedby=error-message-email " : "")
                               aria-required="true" value="@Model.Data.Email" />
                    </div>

                    <div class="form-group @(!string.IsNullOrEmpty(Model.Data.NameError) ? "error" : "")">
                        <label for="Name">
                            <span class="form-label-bold" id="error-message-name">Full name</span>
                            @if (!string.IsNullOrEmpty(Model.Data.NameError))
                            {
                                <span class="error-message">@Model.Data.NameError</span>
                            }
                        </label>
                        <input class="form-control form-control-3-4" id="Name" name="Name" type="text"
                               @(!string.IsNullOrEmpty(Model.Data.NameError) ? " aria-describedby=error-message-name " : "")
                               aria-required="true" value="@Model.Data.Name" />
                    </div>
                    <div class="form-group @(!string.IsNullOrEmpty(Model.Data.RoleError) ? "error" : "")">
                        <fieldset>
                            <legend>
                                <span class="form-label-bold">Team member access</span>
                                <span class="form-hint">Choose the level of access this user can have.</span>
                                @if (!string.IsNullOrEmpty(Model.Data.RoleError))
                                {
                                    <span class="error-message" id="RoleId">@Model.Data.RoleError</span>
                                }
                            </legend>
                            <label class="block-label" for="radio1">
                                <input id="radio1" type="radio" name="Role" value="3" @(Model.Data.Role == Role.Viewer ? "checked" : "") />
                                @(RoleStrings.GetRoleDescription(Role.Viewer))
                            </label>
                            <label class="block-label" for="radio2">
                                <input id="radio2" type="radio" name="Role" value="2" @(Model.Data.Role == Role.Transactor ? "checked" : "") />
                                @(RoleStrings.GetRoleDescription(Role.Transactor))
                            </label>
                            <label class="block-label" for="radio3">
                                <input id="radio3" type="radio" name="Role" value="1" @(Model.Data.Role == Role.Owner ? "checked" : "") />
                                @(RoleStrings.GetRoleDescription(Role.Owner))
                            </label>
                        </fieldset>
                    </div>
                    <input type="hidden" id="HashedId" name="HashedId" value="@Model.Data.HashedAccountId" />
                    <button type="submit" class="button" id="send_invitation">Send invitation</button>
                </form>
            </div>
        </div>

        @section breadcrumb {
            <div class="breadcrumbs">
               <a href="@Url.Action("ViewTeam", "EmployerTeam")", class="back-link">Back to your team</a>
            </div>
        }

src/SFA.DAS.EAS.Web/Views/EmployerTeam/Remove.cshtml
@model SFA.DAS.EAS.Web.OrchestratorResponse<SFA.DAS.EAS.Web.ViewModels.InvitationViewModel>

@{
    var name = Model.Data.Name ?? Model.Data.Email;
    ViewBag.PageID = "page-remove-team-member";
    ViewBag.Title = "Remove team member";
    ViewBag.Section = "team";
}
   
<div class="grid-row">
    <div class="column-two-thirds">
        <h1 class="heading-xlarge">Remove team member</h1>
        @if (!ViewContext.ViewData.ModelState.IsValid)
        {
            foreach (var state in ViewContext.ViewData.ModelState.Values)
            {
                foreach (var error in state.Errors)
                {
                    <div class="error" id="invalidMessage">
                        <p class="error-message">@error.ErrorMessage</p>
                    </div>
                }
            }
        }
        <p class="lede">Are you sure you want to remove @name?</p>
        <div class="form-group">
            <form action="@Url.Action("Remove")" method="POST">
                @Html.AntiForgeryToken()
                <input type="hidden" id="remove" name="remove" value="1" />
                <input type="hidden" id="UserId" name="UserId" value="@Model.Data.Id" />
                <input type="hidden" id="Email" name="Email" value="@Model.Data.Email" />
                <button type="submit" class="button" id="remove_team_member">Yes, remove now</button>
            </form>
            <a href="@Url.Action("Viewteam", "EmployerTeam")" class="button button-link">No, cancel</a>
        </div>
    </div>
</div>

@section breadcrumb {

    <div class="breadcrumbs">
        <a href="@Url.Action("ViewTeam", "EmployerTeam")" class="back-link">Back to your team</a>
    </div>
}

src/SFA.DAS.EAS.Web/Views/EmployerTeam/Review.cshtml
@using SFA.DAS.EAS.Domain
@using SFA.DAS.EAS.Domain.Models.AccountTeam
@using SFA.DAS.EAS.Domain.Models.UserProfile
@using SFA.DAS.EAS.Web

@model OrchestratorResponse<SFA.DAS.EAS.Domain.Models.AccountTeam.TeamMember>

@{
    ViewBag.PageID = "page-review-team-member";
    ViewBag.Title = Model.Data.Name;
    ViewBag.Section = "team";
}

<div class="grid-row">
    <div class="column-two-thirds">
        <h1 class="heading-xlarge">@Model.Data.Name</h1>
        <table>     
            <thead>
                <tr>
                    <th scope="col">Email</th>
                    <th scope="col">What they can do</th>
                    <th></th>
                </tr>
            </thead> 
            <tbody>
                <tr>
                    <td>@Model.Data.Email</td>
                    <td>@RoleStrings.GetRoleDescription(@Model.Data.Role)</td>
                    @if (Model.Data.IsUser)
                    {
                        <td class="link-right">
                            <a href="@Url.Action("ChangeRole","EmployerTeam", new { Model.Data.Email })">Change <span class="vh">role for @Model.Data.Name</span></a>
                        </td>
                    }
                    else
                    {
                        <td></td>
                    }
                </tr>              
            </tbody>
        </table>
      
        @if (@Model.Data.Status == InvitationStatus.Pending || @Model.Data.Status == InvitationStatus.Expired)
        {
            <div class="form-group">
                <form action="@Url.Action("Resend")" method="POST">
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="Email" name="Email" value="@Model.Data.Email" />
                    <button type="submit" class="button" id="resend_invitation">Resend Invitation</button>
                </form>
                <a href="@Url.Action("Cancel", "EmployerTeam",new {email = Model.Data.Email, invitationId = Model.Data.HashedInvitationId })" class="button button-link">Cancel Invitation</a> 
                
            </div>
        }
        @if (@Model.Data.IsUser)
        {
            <form action="@Url.Action("Remove")" method="GET">
                <input type="hidden" id="Email" name="Email" value="@Model.Data.Email" />
                <button type="submit" class="button" id="delete_user">Remove team member</button>
            </form>
         
        }
    </div>
</div>

@section breadcrumb {
    <div class="breadcrumbs">
        <a href="@Url.Action("ViewTeam", "EmployerTeam")" class="back-link">Back to your team</a>
    </div>
}

src/SFA.DAS.EAS.Web/Views/EmployerTeam/ViewTeam.cshtml
@using SFA.DAS.EAS.Domain
@using SFA.DAS.EAS.Domain.Models.AccountTeam
@using SFA.DAS.EAS.Domain.Models.UserProfile
@using SFA.DAS.EAS.Web

@model OrchestratorResponse<SFA.DAS.EAS.Web.ViewModels.EmployerTeamMembersViewModel>

@{
    ViewBag.PageID = "page-manage-team";
    ViewBag.Title = "Manage team members";
    ViewBag.Section = "team";

    if (!string.IsNullOrEmpty(Model.FlashMessage?.HiddenFlashMessageInformation))
    {
        ViewBag.PageID = Model.FlashMessage.HiddenFlashMessageInformation;
    }
    
}

<div class="grid-row header-index">
    <div class="column-two-thirds">
        <h1 class="heading-xlarge">Your team</h1>
        @if (Model.Data.TeamMembers.Count == 0)
        {
            <p>TODO : EMPTY STATE</p>
        }
        else
        {
            <p class="lede">
                Invite members, control what they can do, remove members and cancel or resend invitations.
            </p>
        }
    </div>
    <div class="column-one-third">
        <form action="@Url.Action("Invite")" method="get">
            <input class="button action-add" id="addNewUser" type="submit" value="Invite a new member">
        </form>
    </div>
</div>

@if (Model.Data.TeamMembers.Count > 0)
{
    <div class="grid-row">
        <div class="column-full">
            <table>
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">What they can do</th>
                        <th scope="col">Status</th>
                        <th scope="col"><span class="vh">Action</span></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var teamMember in Model.Data.TeamMembers)
                {
                        <tr>
                            <td>
                                <span>@teamMember.Name</span>
                                <span class="responsive-detail mobile-hide">@teamMember.Email</span>
                            </td>
                            <td>@RoleStrings.GetRoleDescription(teamMember.Role)</td>
                            <td>@InvitationStatusStrings.ToString(teamMember.Status)</td>
                            <td class="link-right">
                                <a aria-label="View details for @teamMember.Name"
                                   href="@Url.Action("Review", new { email = teamMember.Email })">View<span class="vh"> details for @teamMember.Name</span></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
           
        </div>
    </div>
}

        @section breadcrumb {
            <div class="breadcrumbs">
                <ol role="navigation">
                    <li><a href="@Url.Action("Index", "EmployerTeam")">Home</a></li>
                    <li>Your team</li>
                </ol>
            </div>
        }